### ISSUE TITLE
2.1 hub hack is just as possible as 2.0

### ISSUE THREAD

**Issue by levihb** [Rocka84/pushing-hue#6]
> known hw attack impossible

Just wondering why you said that? Corrupting the data coming from the flash still works just fine. I and many others have rooted the 2.1 hub. I just bridged the DO pin from the flash chip to ground, and then was dropped into a root shell.

**Comment by digitallyserviced** [comment]
It would seem root and opkg is available on latest FW for 2.1 devices. 
They are missing a lot of the kernel modules that would enable wifi. Since the kernel is 4.4 and the openwrt they based it from used  3.x something, we cannot use opkg kmod's.

Anyone have an ideas or are we relegated to having compile from source the kernel with the modules we want?
Does anyone have a dump of earlier FW's that have the proper kernel modules included?

**Comment by Rocka84** [comment]
> Just wondering why you said that?
Because of my limited understanding at the time ;-)
If I remember correctly, I just wasn't able to find the pin that needed to be grounded. So as I still had a 2.0 hub, I didn't spend much time searching on the 2.1 hub and just went back to existing tutorials for the older version.
Sry, I'm not that much of a hardware guy - even less back then.
